openapi: 3.0.1
info:
  title: API de Integración - Inventario
  description: Endpoints públicos disponibles para sistemas externos autenticados como CLIENTE.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
    description: Servidor local

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Producto:
          type: object
          properties:
            id:
              type: integer
            nombre:
              type: string
            descripcion:
              type: string
            categoria:
              type: string
            precio:
              type: number
            cantidad:
              type: integer

security:
  - bearerAuth: []

paths:

  /productos:
    get:
      tags:
        - Productos
      summary: Obtener lista de productos
      description: Devuelve la lista paginada de productos visibles para el cliente.
      parameters:
        - name: page
          in: query
          description: Página solicitada (por defecto 0)
          schema:
            type: integer
            example: 0
        - name: size
          in: query
          description: Cantidad de elementos por página (por defecto 10)
          schema:
            type: integer
            example: 10
      responses:
        '200':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/Producto'
        '401':
          description: No autorizado (token inválido o ausente)

  /productos/{id}:
    get:
      tags:
        - Productos
      summary: Obtener un producto por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Detalles del producto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Producto'
        '404':
          description: Producto no encontrado
        '401':
          description: No autorizado

  /productos/filtro:
    get:
      summary: Buscar productos por filtros
      parameters:
        - name: nombre
          in: query
          schema:
            type: string
            example: Laptop
        - name: categoria
          in: query
          schema:
            type: string
            example: ELECTRONICA
        - name: precioMin
          in: query
          schema:
            type: number
            format: double
            example: 100.00
        - name: precioMax
          in: query
          schema:
            type: number
            format: double
            example: 5000.00
        - name: busqueda
          in: query
          schema:
            type: string
            example: Laptop
        - name: page
          in: query
          schema:
            type: integer
            default: 0
            example: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 10
            example: 10
      responses:
        '200':
          description: Resultados filtrados
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/Producto'

  /productos/listar-categorias:
    get:
      tags:
        - Productos
      summary: Listar categorías de producto
      responses:
        '200':
          description: Lista de categorías
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string